import {StyleSheet} from 'react-native';
import colors from '../common/colors';

const style = (width, height) =>
  StyleSheet.create({
    mainContainer: {
      marginVertical: 15,
      overflow: 'hidden',
      padding: 15,
      backgroundColor: colors.white_level_1,
      flex: 1,
      marginTop: 0,
    },
    profileContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderBottomColor: colors.secondaryBlue,
      paddingVertical: 15,
    },
    profileInnerContainerGlow: {
      height: height * 0.105,
      width: width * 0.2,
      borderRadius: width * 0.2,
      backgroundColor: colors.greenGlow,
      justifyContent: 'center',
      alignItems: 'center',
    },
    profileInnerContainer: {
      // height: 70,
      // width: 70,
      borderRadius: width * 0.2,
      backgroundColor: colors.white_level_3,
      justifyContent: 'center',
      alignItems: 'center',
    },
    image: {
      height: height * 0.1,
      width: width * 0.19,
      resizeMode: 'contain',
      borderRadius: width * 0.2,
    },
    screensContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 5,
      marginVertical: 8,
    },
    screensInnerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    drawerIcon: {
      resizeMode: 'contain',
      height: 28,
      width: 28,
      marginRight: 10,
    },
    drawerNextIcon: {
      resizeMode: 'contain',
      height: 28,
      width: 28,
      backgroundColor: colors.tertiaryGreen,
      borderRadius: 28 / 2,
      overflow: 'hidden',
    },
    screenName: {
      fontSize: 19,
      fontFamily: 'Lato-Bold',
      color: colors.black,
      textAlign: 'center',
      // marginBottom: 20,
    },
    logoutContainer: {
      // marginVertical: 15,
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderWidth: 1,
      width: '50%',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 20,
      backgroundColor: colors.greenGlow,
      // borderWidth: 1,
    },
    logoutText: {
      color: colors.black_level_2,
      fontFamily: 'Lato-Bold',
      fontSize: 17,
      marginHorizontal: 10,
    },
    supportContainer: {
      // paddingVertical: 10,
      backgroundColor: colors.secondaryGreen,
      marginTop: 20,
      borderRadius: 20,
      paddingTop: 18,
      padding: 10,
    },
    supportHead: {
      fontSize: 20,
      fontFamily: 'Lato-Black',
      color: colors.black,
      marginBottom: 8,
    },
    supportText: {
      fontSize: 16,
      fontFamily: 'Lato-Regular',
      color: colors.black,
      lineHeight: 20,
    },
    contactContainer: {
      paddingHorizontal: 15,
      paddingVertical: 9,
      borderWidth: 1,
      width: '50%',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 20,
      backgroundColor: colors.inKartGreen,
      flexDirection: 'row',
      marginTop: 11,
      // marginLeft: 11,
    },
    contactText: {
      color: colors.white,
      fontFamily: 'Lato-Bold',
      fontSize: 17,
      paddingHorizontal: 10,
    },
  });

export default style;
